INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Algoritmos II',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Administração de Redes',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Avaliação de Desempenho',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Banco de Dados II',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Computação Gráfica',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Computação Móvel',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Computação Paralela',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Engenharia da Informação',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Engenharia de Requisitos',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Engenharia de Software II',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Hipermídia',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Interface Humano-Computador',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Laboratório de Engenharia de Software',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Processamento de Imagens',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Programação Distribuída',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Redes de Computadores II',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Sistemas Distribuídos',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Sistemas Inteligentes',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Sistemas Operacionais II',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Tópicos Especiais em Ciência da Computação',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Circuitos Digitais II',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Introdução ao Controle de Processos',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Controle de Processos e Automação',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Microprocessadores',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Laboratório de Circuitos Digitais II',30,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Lab. de Microprocessadores',30,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('T.E.C.C – Sistemas de Informações Geográficas',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('T.E.C.C – Introdução à Mineração de Dados',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('T.E.C.C – Visão Computacional',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('T.E.C.C – Jogos Digitais',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('T.E.C.C – Introdução à Criptografia',60,'Grupo I');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Computação e Sociedade',60,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Contabilidade Geral',60,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Direito Usual para Computação',60,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Economia',60,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Filosofia',45,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Gerência de Tecnologia da Informação',60,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Inglês I',45,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Inglês II',45,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Introdução à Administração',60,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Psicologia',45,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Sociologia',60,'Grupo II');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Atividades Complementares',180,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Estágio Supervisionado',360,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Monografia I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Monografia II',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Introdução à Computação',45,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Algoritmos I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Cálculo Diferencial e Integral I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Cálculo Diferencial e Integral II',90,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Cálculo Diferencial e Integral III',90,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Cálculo Vetorial e Geometria Analítica',90,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Metodologia Científica',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Física I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Física II',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Linguagem de Programação',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Matemática Discreta e Lógica',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Álgebra Linear',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Circuitos Digitais I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Física Experimental I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Arquitetura de Computadores',30,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Estrutura de Dados I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Paradígmas de Programação',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Linguagens Formais e Autômatos',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Laboratório de Circuitos Digitais I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Estrutura de Dados II',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Engenharia de Software I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Teoria da Computação',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Sistemas Operacionais I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Estatística e Probabilidade',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Processo de Desenvolvimento de Software',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Redes de Computadores I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Banco de Dados I',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Processos Estocásticos',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Compiladores',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Cálculo Numérico',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Inteligência Artificial',60,'Obrigatória');
INSERT INTO disciplinas(nome,carga_horaria,tipo) VALUES ('Pesquisa Operacional',60,'Obrigatória');
